import type { Metadata } from "next";
import "./globals.css";
import { Archivo } from "next/font/google";
import { CartProvider } from "@/components/reusable/CartContext";
import { CartModalProvider } from "@/components/reusable/CartModalContext";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "./auth-provider";

const archivo = Archivo({ 
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-archivo'
});

export const metadata: Metadata = {
  title: "Had Cashier",
  description: "Generated by Had Code",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased select-none`}
      >
        <AuthProvider>
          <CartProvider>
            <CartModalProvider>
                {children}
                <Toaster richColors position="top-center" />
            </CartModalProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
